# Facebook Auth
FACEBOOK_APP_ID: "2306669629576223"
FACEBOOK_APP_SECRET: "b12249946b7d8819c32de3ccb6be2ffb"

# Google Auth
GOOGLE_OAUTH2_APP_ID: "729130747818-bdf6p3ls04rehqc42mv3ipeddg529fq4.apps.googleusercontent.com"
GOOGLE_OAUTH2_APP_SECRET: "1CYxie350CypSSOV4zPnnARp"

# Google Account
GMAIL_USERNAME: "tranlethanhdat120895@gmail.com"
GMAIL_PASSWORD: "Thanhdat128195"
